version: "3.7"

services:
  kong:
    image: kong:2.4
    restart: always
    container_name: kong
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: kong.yml
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: "0.0.0.0:8001"
    ports:
      - "80:8000"
      - "443:8001"
      - "8001:8001"
    volumes:
      - "./kong/kong.yml:/kong.yml"
    networks:
      - cpn-quiz

  portainer:
    image: portainer/portainer-ce:latest
    ports:
      - 9000:9000
      - 9443:9443
    command: --http-enabled
    volumes:
      - ./portainer/portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

  cpn-quiz-db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - ./database/cpn_quiz_db:/var/lib/postgresql/data
    networks:
      - cpn-quiz

  cpn-quiz-keycload-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRESQL_DB}
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASS: ${POSTGRESQL_PASS}
    ports:
      - '5434:5434'
    volumes:
      - ./keycloak/keycloak_data:/var/lib/postgresql/data
    networks:
      - cpn-quiz-keycloak

  cpn-quiz-keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: cpn-quiz-keycloak
    environment:
      PROXY_ADDRESS_FORWARDING: true
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
      KC_LOG_LEVEL: debug
      KC_DB: postgres
      KC_DB_URL: 'jdbc:postgresql://cpn-quiz-keycload-db/keycloak'
      KC_DB_PORT: 5434
      KC_DB_USERNAME: ${POSTGRESQL_USER}
      KC_DB_PASSWORD: ${POSTGRESQL_PASS}
      KC_DB_SCHEMA: public
      KC_HOSTNAME: ${KC_HOSTNAME}
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HOSTNAME_STRICT: false
      KC_PROXY: none
      HTTP_ADDRESS_FORWARDING: true
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    command: start
    volumes:
      - ./keycloak/keycloak/realm.json:/opt/keycloak/data/import/realm.json
    depends_on:
      - cpn-quiz-keycload-db
    ports:
      - '8080:8080'
    restart: always
    networks:
      - cpn-quiz-keycloak

  redis:
    image: "redis:alpine"
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}
    volumes:
      - "./redis/redis_data:/data"
    networks:
      - cpn-quiz

  #CPN Quiz API
  cpn-quiz-api-authentication:
    build:
      context: ./api/cpn-quiz-api-authentication-go
      dockerfile: Dockerfile.dev
    restart: always
    depends_on:
      - kong
      - cpn-quiz-db
    container_name: cpn-quiz-api-authentication
    links:
      - cpn-quiz-db
      - redis
      - cpn-quiz-keycloak
    networks:
      - cpn-quiz
      - cpn-quiz-keycloak

  cpn-quiz-api-file-manage:
    build:
      context: ./api/cpn-quiz-api-file-manage-go
      dockerfile: Dockerfile.dev
    restart: always
    depends_on:
      - kong
      - cpn-quiz-db
    container_name: cpn-quiz-api-file-manage
    links:
      - cpn-quiz-db
    volumes:
      - "./api/cpn-quiz-api-file-manage-go/storage:/app/storage"
    networks:
      - cpn-quiz

  cpn-quiz-api-mailer:
    build:
      context: ./api/cpn-quiz-api-mailer-go
      dockerfile: Dockerfile.dev
    restart: always
    depends_on:
      - kong
      - cpn-quiz-db
    links:
      - cpn-quiz-db
      - redis
    container_name: cpn-quiz-api-mailer
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    networks:
      - cpn-quiz

  cpn-quiz-schedule-messenger:
    build:
      context: ./schedule/cpn-quiz-schedule-messenger-go
      dockerfile: Dockerfile.dev
    restart: always
    depends_on:
      - cpn-quiz-db
      - redis
    links:
      - cpn-quiz-db
      - redis
    container_name: cpn-quiz-schedule-messenger
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    networks:
      - cpn-quiz

networks:
  cpn-quiz:
    name: cpn-quiz
  cpn-quiz-keycloak:
    name: cpn-quiz-keycloak
    external: true

volumes:
  portainer_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './monitoring/portainer/portainer_data'
    external: false
  cpn_quiz_db:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './database/cpn_quiz_db'
    external: false
  redis_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './redis/redis_data'
    external: false
  keycloak:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './keycloak/keycloak'
    external: false
  keycloak_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './keycloak/keycloak_data'
    external: false
  cpn_quiz_api_file_manage_go:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './api/cpn-quiz-api-file-manage-go/storage'
    external: false
