build:
  date: 2022/04/07
  number: 0

service:
  name: cpn-quiz-api-authentication-go
  port: 8080
  domain: localhost
  endpoint: /cpn-quiz-api-authentication-go

kibana:
  suffix: cpn-quiz-api-authentication-go
