apiVersion: apps/v1
kind: Deployment
metadata:
  name: schedule-project-template-go
spec:
  selector:
    matchLabels:
      app: schedule-project-template-go
  template:
    metadata:
      labels:
        app: schedule-project-template-go
    spec:
      containers:
      - name: primary
        env:
        - name: env
          value: prod
        resources:
          limits:
            memory: 200Mi
          requests:
            memory: 100Mi
