apiVersion: apps/v1
kind: Deployment
metadata:
  name: schedule-project-template-go
  labels:
    app: schedule-project-template-go
spec:
  replicas: 1
  selector:
    matchLabels:
      app: schedule-project-template-go
  template:
    metadata:
      labels:
        app: schedule-project-template-go
    spec:
      containers:
      - name: primary
        image: ${image}
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          limits:
            memory: 200Mi
          requests:
            memory: 100Mi
      imagePullSecrets:
      - name: harbor-regcred
---
kind: Service
apiVersion: v1
metadata:
  name: schedule-project-template-go
spec:
  selector:
    app: schedule-project-template-go
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: schedule-project-template-go
spec:
  rules:
  - host: $(ING_NAME)-${namespace}-kolpos.pea.co.th
    http:
      paths:
      - backend:
          service:
            name: schedule-project-template-go
            port:
              number: 80
        path: /
        pathType: Prefix