version: "3.7"
services:
  redis:
    image: "redis:alpine"
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --requirepass Wh5a2N7CJve36HRpSZAukKMQDPLdmYG9tTcbxrz4
    volumes:
      - redis_data:/data

networks:
  default:
    name: cpn-quiz

volumes:
  redis_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: './redis_data'
    external: false
