build:
  date: 2024/03/17
  author: gasxhermvc

service:
  name: cpn-quiz-api-api-mailer
  port: 80
  domain: localhost
  endpoint: /cpn-quiz-api-api-mailer

kibana:
  suffix: cpn-quiz-api-api-mailer
